"""
Configuration Manager Module
Manages centralized agent configuration and groups
"""

import os
import yaml
import logging
import subprocess
import shutil
from typing import Dict, Any, Optional, List
from pathlib import Path


class ConfigManager:
    """Manages Wazuh configuration"""
    
    def __init__(self, config: Dict[str, Any], logger: logging.Logger):
        self.config = config
        self.logger = logger
        # Use configurable paths from config
        paths = config.get('paths', {})
        self.wazuh_config_path = Path(paths.get('wazuh_config', '/var/ossec/etc'))
        self.shared_config_path = Path(paths.get('wazuh_shared', '/var/ossec/etc/shared'))
        self.project_dir = Path(__file__).parent.parent
        self.templates_dir = self.project_dir / "templates"
    
    def configure_agents(self) -> bool:
        """
        Main configuration method
        Configures agent groups and centralized configuration
        """
        self.logger.info("Starting agent configuration...")
        
        try:
            # Create agent groups
            if not self.create_agent_groups():
                self.logger.error("Failed to create agent groups")
                return False
            
            # Generate agent.conf for each group
            if not self.generate_agent_configs():
                self.logger.error("Failed to generate agent configurations")
                return False
            
            # Validate configurations
            if not self.validate_agent_configs():
                self.logger.error("Configuration validation failed")
                return False
            
            self.logger.info("Agent configuration completed successfully")
            return True
            
        except Exception as e:
            self.logger.error(f"Agent configuration failed: {str(e)}")
            return False
    
    def create_agent_groups(self) -> bool:
        """Create agent groups based on configuration"""
        self.logger.info("Creating agent groups...")
        
        agent_groups = self.config.get('agent_groups', {}).get('groups', {})
        
        for group_name, group_config in agent_groups.items():
            try:
                group_path = self.shared_config_path / group_name
                group_path.mkdir(parents=True, exist_ok=True)
                
                # Set permissions
                os.chmod(group_path, 0o770)
                shutil.chown(group_path, 'wazuh', 'wazuh')
                
                self.logger.info(f"✓ Created group: {group_name}")
                
            except Exception as e:
                self.logger.error(f"Failed to create group {group_name}: {str(e)}")
                return False
        
        self.logger.info(f"Created {len(agent_groups)} agent groups")
        return True
    
    def generate_agent_configs(self) -> bool:
        """Generate agent.conf files for each group"""
        self.logger.info("Generating agent configurations...")
        
        agent_groups = self.config.get('agent_groups', {}).get('groups', {})
        
        for group_name, group_config in agent_groups.items():
            try:
                agent_conf = self.generate_agent_conf_content(group_name, group_config)
                
                # Write to temporary file first
                group_path = self.shared_config_path / group_name
                temp_file = group_path / 'agent.conf.tmp'
                
                with open(temp_file, 'w') as f:
                    f.write(agent_conf)
                
                # Set permissions
                os.chmod(temp_file, 0o660)
                shutil.chown(temp_file, 'wazuh', 'wazuh')
                
                # Validate configuration
                if self.validate_agent_conf(temp_file):
                    # Move to final location
                    final_file = group_path / 'agent.conf'
                    temp_file.rename(final_file)
                    self.logger.info(f"✓ Generated config for group: {group_name}")
                else:
                    self.logger.error(f"Validation failed for group: {group_name}")
                    return False
                    
            except Exception as e:
                self.logger.error(f"Failed to generate config for {group_name}: {str(e)}")
                return False
        
        return True
    
    def generate_agent_conf_content(self, group_name: str, group_config: Dict[str, Any]) -> str:
        """Generate agent.conf XML content for a group"""
        
        config = group_config.get('configuration', {})
        
        # Build XML content
        xml_content = f"""<!-- Agent configuration for group: {group_name} -->
<!-- Generated by Wazuh Deployer -->
<!-- Description: {group_config.get('description', '')} -->

"""
        
        # Add labels
        labels = group_config.get('labels', [])
        if labels:
            xml_content += "<labels>\n"
            for label in labels:
                # Parse label in format "key=value"
                if '=' in label:
                    key, value = label.split('=', 1)
                    xml_content += f'  <label key="{key}">{value}</label>\n'
                else:
                    # If no separator, use label as both key and value
                    xml_content += f'  <label key="{label}">{label}</label>\n'
            xml_content += "</labels>\n\n"
        
        # Add syscollector configuration
        syscollector = config.get('syscollector', {})
        if syscollector and syscollector.get('enabled'):
            xml_content += self.generate_syscollector_config(syscollector)
        
        # Add vulnerability detection
        vuln_detection = config.get('vulnerability_detection', {})
        if vuln_detection and vuln_detection.get('enabled'):
            xml_content += self.generate_vulnerability_config(vuln_detection)
        
        # Add SCA configuration
        sca = config.get('sca', {})
        if sca and sca.get('enabled'):
            xml_content += self.generate_sca_config(sca)
        
        # Add FIM configuration
        fim = config.get('fim', {})
        if fim and fim.get('enabled'):
            xml_content += self.generate_fim_config(fim)
        
        # Add log configuration
        logs = config.get('logs', [])
        if logs:
            xml_content += self.generate_log_config(logs)
        
        # Add Docker listener
        docker = config.get('docker_listener')
        if docker and docker.get('enabled'):
            xml_content += self.generate_docker_config(docker)
        
        # Add anti-tampering
        anti_tampering = config.get('anti_tampering', {})
        if anti_tampering.get('enabled'):
            xml_content += self.generate_anti_tampering_config(anti_tampering)
        
        # Add cloud integrations
        cloud = config.get('cloud_integrations', {})
        if cloud:
            xml_content += self.generate_cloud_integrations_config(cloud)
        
        return xml_content
    
    def generate_syscollector_config(self, syscollector: Dict[str, Any]) -> str:
        """Generate syscollector configuration"""
        xml = """<wodle name="syscollector">
  <disabled>no</disabled>
"""
        if syscollector.get('interval'):
            xml += f'  <interval>{syscollector["interval"]}</interval>\n'
        if syscollector.get('scan_on_start'):
            xml += f'  <scan_on_start>yes</scan_on_start>\n'
        if syscollector.get('hardware'):
            xml += '  <hardware>yes</hardware>\n'
        if syscollector.get('os'):
            xml += '  <os>yes</os>\n'
        if syscollector.get('network'):
            xml += '  <network>yes</network>\n'
        if syscollector.get('packages'):
            xml += '  <packages>yes</packages>\n'
        ports_all = syscollector.get('ports_all', False)
        xml += f'  <ports all="{"yes" if ports_all else "no"}">yes</ports>\n'
        if syscollector.get('processes'):
            xml += '  <processes>yes</processes>\n'
        if syscollector.get('users'):
            xml += '  <users>yes</users>\n'
        if syscollector.get('groups'):
            xml += '  <groups>yes</groups>\n'
        if syscollector.get('services'):
            xml += '  <services>yes</services>\n'
        if syscollector.get('browser_extensions'):
            xml += '  <browser_extensions>yes</browser_extensions>\n'
        
        xml += """  <synchronization>
    <max_eps>10</max_eps>
  </synchronization>
</wodle>

"""
        return xml
    
    def generate_vulnerability_config(self, vuln: Dict[str, Any]) -> str:
        """Generate vulnerability detection configuration"""
        xml = """<vulnerability-detection>
  <enabled>yes</enabled>
"""
        if vuln.get('index_status'):
            xml += '  <index-status>yes</index-status>\n'
        if vuln.get('feed_update_interval'):
            xml += f'  <feed-update-interval>{vuln["feed_update_interval"]}</feed-update-interval>\n'
        
        xml += "</vulnerability-detection>\n\n"
        return xml
    
    def generate_sca_config(self, sca: Dict[str, Any]) -> str:
        """Generate SCA configuration"""
        xml = """<sca>
  <enabled>yes</enabled>
"""
        if sca.get('scan_on_start'):
            xml += '  <scan_on_start>yes</scan_on_start>\n'
        if sca.get('interval'):
            xml += f'  <interval>{sca["interval"]}</interval>\n'
        if sca.get('skip_nfs'):
            xml += '  <skip_nfs>yes</skip_nfs>\n'
        
        xml += "</sca>\n\n"
        return xml
    
    def generate_fim_config(self, fim: Dict[str, Any]) -> str:
        """Generate FIM configuration"""
        xml = """<syscheck>
  <disabled>no</disabled>
"""
        if fim.get('frequency'):
            xml += f'  <frequency>{fim["frequency"]}</frequency>\n'
        
        directories = fim.get('directories', [])
        if isinstance(directories, list):
            for dir_config in directories:
                if isinstance(dir_config, dict):
                    path = dir_config.get('path', '')
                    check_all = dir_config.get('check_all', True)
                    whodata = dir_config.get('whodata', False)
                    xml += f'  <directories check_all="{"yes" if check_all else "no"}" '
                    xml += f'whodata="{"yes" if whodata else "no"}">{path}</directories>\n'
                elif isinstance(dir_config, str):
                    xml += f'  <directories check_all="yes">{dir_config}</directories>\n'
        
        nodiff = fim.get('nodiff_files', [])
        for nodiff_file in nodiff:
            xml += f'  <nodiff>{nodiff_file}</nodiff>\n'
        
        if fim.get('skip_nfs'):
            xml += '  <skip_nfs>yes</skip_nfs>\n'
        if fim.get('skip_dev'):
            xml += '  <skip_dev>yes</skip_dev>\n'
        if fim.get('skip_proc'):
            xml += '  <skip_proc>yes</skip_proc>\n'
        if fim.get('skip_sys'):
            xml += '  <skip_sys>yes</skip_sys>\n'
        
        xml += '  <process_priority>10</process_priority>\n'
        xml += '  <max_eps>50</max_eps>\n'
        
        xml += """  <synchronization>
    <enabled>yes</enabled>
    <interval>5m</interval>
    <max_eps>10</max_eps>
  </synchronization>
</syscheck>

"""
        return xml
    
    def generate_log_config(self, logs: List[Dict[str, str]]) -> str:
        """Generate log configuration"""
        xml = ""
        for log_config in logs:
            location = log_config.get('location', '')
            format_type = log_config.get('format', 'syslog')
            xml += f'<localfile>\n'
            xml += f'  <location>{location}</location>\n'
            xml += f'  <log_format>{format_type}</log_format>\n'
            xml += '</localfile>\n'
        
        xml += "\n"
        return xml
    
    def generate_docker_config(self, docker: Dict[str, Any]) -> str:
        """Generate Docker listener configuration"""
        xml = """<wodle name="docker-listener">
  <disabled>no</disabled>
"""
        if docker.get('interval'):
            xml += f'  <interval>{docker["interval"]}</interval>\n'
        if docker.get('attempts'):
            xml += f'  <attempts>{docker["attempts"]}</attempts>\n'
        if docker.get('run_on_start'):
            xml += '  <run_on_start>yes</run_on_start>\n'
        
        xml += "</wodle>\n\n"
        return xml
    
    def generate_anti_tampering_config(self, anti_tampering: Dict[str, Any]) -> str:
        """Generate anti-tampering configuration"""
        xml = """<agent_config os="linux">
  <anti_tampering>
"""
        if anti_tampering.get('package_uninstallation'):
            xml += '    <package_uninstallation>yes</package_uninstallation>\n'
        
        xml += """  </anti_tampering>
</agent_config>

"""
        return xml
    
    def generate_cloud_integrations_config(self, cloud: Dict[str, Any]) -> str:
        """Generate cloud integrations configuration"""
        xml = ""
        
        # AWS
        aws = cloud.get('aws', {})
        if aws.get('enabled'):
            xml += """<wodle name="aws-s3">
  <disabled>no</disabled>
"""
            if aws.get('interval'):
                xml += f'  <interval>{aws["interval"]}</interval>\n'
            xml += '  <run_on_start>yes</run_on_start>\n'
            xml += '  <skip_on_error>yes</skip_on_error>\n'
            xml += '  <bucket type="cloudtrail">\n'
            xml += '    <name>YOUR_AWS_BUCKET</name>\n'
            xml += '    <aws_profile>default</aws_profile>\n'
            xml += '  </bucket>\n'
            xml += "</wodle>\n\n"
        
        # GCP
        gcp = cloud.get('gcp', {})
        if gcp.get('enabled'):
            xml += """<gcp-pubsub>
  <pull_on_start>yes</pull_on_start>
"""
            if gcp.get('interval'):
                xml += f'  <interval>{gcp["interval"]}</interval>\n'
            xml += '  <project_id>YOUR_PROJECT_ID</project_id>\n'
            xml += '  <subscription_name>YOUR_SUBSCRIPTION_ID</subscription_name>\n'
            xml += '  <credentials_file>/var/ossec/wodles/gcloud/auth.json</credentials_file>\n'
            xml += "</gcp-pubsub>\n\n"
        
        # GitHub
        github = cloud.get('github', {})
        if github.get('enabled'):
            xml += """<github>
  <enabled>yes</enabled>
"""
            if github.get('interval'):
                xml += f'  <interval>{github["interval"]}</interval>\n'
            xml += '  <time_delay>1m</time_delay>\n'
            xml += '  <curl_max_size>1M</curl_max_size>\n'
            xml += '  <only_future_events>yes</only_future_events>\n'
            xml += '  <api_auth>\n'
            xml += '    <org_name>YOUR_ORG_NAME</org_name>\n'
            xml += '    <api_token>YOUR_API_TOKEN</api_token>\n'
            xml += '  </api_auth>\n'
            xml += '  <api_parameters>\n'
            xml += '    <event_type>all</event_type>\n'
            xml += '  </api_parameters>\n'
            xml += "</github>\n\n"
        
        return xml
    
    def validate_agent_conf(self, config_file: Path) -> bool:
        """Validate agent.conf using verify-agent-conf"""
        try:
            result = subprocess.run(
                ['/var/ossec/bin/verify-agent-conf', '-f', str(config_file)],
                capture_output=True,
                text=True
            )
            
            if result.returncode == 0:
                self.logger.info(f"✓ Configuration valid: {config_file}")
                return True
            else:
                self.logger.error(f"✗ Configuration invalid: {config_file}")
                self.logger.error(result.stderr)
                return False
                
        except Exception as e:
            self.logger.error(f"Validation failed for {config_file}: {str(e)}")
            return False
    
    def validate_agent_configs(self) -> bool:
        """Validate all agent configurations"""
        self.logger.info("Validating all agent configurations...")
        
        agent_groups = self.config.get('agent_groups', {}).get('groups', {})
        
        for group_name in agent_groups.keys():
            config_file = self.shared_config_path / group_name / 'agent.conf'
            if config_file.exists():
                if not self.validate_agent_conf(config_file):
                    return False
        
        self.logger.info("All agent configurations validated successfully")
        return True
